{
  parserClass="org.dylanfoundry.deft.filetypes.lid.parser.LIDParser"
  stubParserClass="org.dylanfoundry.deft.parser.GeneratedParserUtilBase"
 
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
 
  psiClassPrefix="LID"
  psiImplClassSuffix="Impl"
  psiPackage="org.dylanfoundry.deft.filetypes.lid.psi"
  psiImplPackage="org.dylanfoundry.deft.filetypes.lid.psi.impl"
 
  elementTypeHolderClass="org.dylanfoundry.deft.filetypes.lid.psi.LIDTypes"
  elementTypeClass="org.dylanfoundry.deft.filetypes.lid.psi.LIDElementType"
  tokenTypeClass="org.dylanfoundry.deft.filetypes.lid.psi.LIDTokenType"
}
 
lidFile ::= items

items ::= item*
 
item ::= (item_key SEPARATOR values)

item_key ::= KEY

values ::= (item_value CRLF?)*

item_value ::= VALUE
